version: '3.8'
services:
  ${BLUE_CONTAINER}:
    container_name: ${BLUE_CONTAINER}
    image: ${SERVICE_IMAGE}:latest
    ports:
      - "${BLUE_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

  ${GREEN_CONTAINER}:
    container_name: ${GREEN_CONTAINER}
    image: ${SERVICE_IMAGE}:latest
    ports:
      - "${GREEN_PORT}:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
