version: '3.8'
services:
  ${BLUE_CONTAINER}:
    container_name: ${BLUE_CONTAINER}
    image: ${SERVICE_IMAGE}:latest
    ports:
      - "${BLUE_PORT}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://${API_SERVER_DOMAIN}
    networks:
      - app-network

  ${GREEN_CONTAINER}:
    container_name: ${GREEN_CONTAINER}
    image: ${SERVICE_IMAGE}:latest
    ports:
      - "${GREEN_PORT}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://${API_SERVER_DOMAIN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
