version: "3.8"

services:
  # Blue 배포
  fabtable-next-blue:
    container_name: fabtable-next-blue
    image: fabtable-next-docker:latest
    ports:
      - "8885:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.fabtable.fnfworks.com
    networks:
      - blue-green-net

  # Green 배포
  fabtable-next-green:
    container_name: fabtable-next-green
    image: fabtable-next-docker:latest
    ports:
      - "8886:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.fabtable.fnfworks.com
    networks:
      - blue-green-net

networks:
  blue-green-net:
    driver: bridge
